# config.yml is meant for settings which you are expected to set up once and rarely edit after that. 
# If you find yourself editing this file very often, consider using Jekyll's data files feature.
#
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. 
# If you change this file, please ^C the above process and restart it.
#
# YAML quick reference: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# You can create any custom variable you would like, and they will be accessible
# in the templates / HTML files via {{ site.myvariable }}.

title: STEM Scholars
description: >- # this means to ignore newlines until "baseurl:". Use keywords for Google search results
  A step-by-step guide and roadmap for elementary, middle and high school students on
  which activities to pursue in all STEM realted fields, e.g., math, coding, robotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stemscholars.github.io"
github_username: stemscholars
google_analytics: UA-177852108-1

plugins:
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  robocomp:
